### ISSUE TITLE
Error on line 136

### ISSUE THREAD

**Issue by Pok4** [criativamos/Paginator#1]
I'm getting random errors at line 136 in Paginator.php

[Wed Sep 28 01:22:41.302964 2016] [:error] [pid 2505] [client 84.238.184.98:57603] PHP Notice:  Trying to get property of non-object in /home/predizvi/public_html/vendor/criativamos/paginator/Paginator.php on line 136, referer: last_liked.php

I'm getting this errors on pages that i not even using this pagination ?! Randomly on random files...
I dont know what is happening. Can you fix it ?

```
private function total()
{
    $pattern = '/^(?:SELECT)(.+)(?:FROM)/is';
    preg_match($pattern, $this->originalQuery, $matches);
    $query = str_replace($matches[1], ' COUNT(0) AS TOTAL ', $this->originalQuery);
    $stmt = $this->db->prepare($query);
    $stmt->execute($this->parameters);
  ##   **$this->results['total'] = (int) $stmt->fetch(\PDO::FETCH_OBJ)->TOTAL;**
    return $this->results['total'];
}
```

Everything works correctly, but this error is annoying..

**Comment by criativamos** [comment]
Sorry for delay. The error was fixed.
